services:
  app:
    build: ./app
    volumes:
      - ./app:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://логин_бд:пароль_бд@db:5432/имя_бд
      - TZ=Europe/Moscow
    ports:
      - '8000:8000'
    restart: always

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: имя_бд
      POSTGRES_USER: логин_бд
      POSTGRES_PASSWORD: пароль_бд
    ports:
      - '5438:5432'
    restart: always

volumes:
  db_data:
